/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerWorkArea;

import business.organization.CustomerOrganization;
import Business.customer.MasterOrderList;
import Business.customer.PersonalisedOrder;
import Business.customer.PersonalisedOrderItem;
//import business.customer.CustomizedOrderItem;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.enterprise.customerCareEnterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.StoreOrganization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mrunalbhalerao
 */
public class PersonalizeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonalizeJPanel
     */
    private JPanel userProcessContainer;
    private MasterOrderList mod;
    private CustomerOrganization customerOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;
    private int count;
    
    public PersonalizeJPanel(JPanel userProcessContainer, Organization organization, UserAccount account, Enterprise enterprise, Ecosystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.customerOrganization = (CustomerOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        
        customerName.setText(account.getUsername());
        
    }
    
        PersonalisedOrder order = new PersonalisedOrder();
        PersonalisedOrderItem oi = new PersonalisedOrderItem();
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbQuantity = new javax.swing.JComboBox<>();
        cmbCategory = new javax.swing.JComboBox();
        cmbColor = new javax.swing.JComboBox();
        cmbSize = new javax.swing.JComboBox<>();
        cmbFabricType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbText = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbTextLocation = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmbDesignTechnique = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbStyle = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        customerName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));

        backJButton.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(102, 0, 51));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 51));
        jLabel8.setText("Hello!");

        btnAdd.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(102, 0, 51));
        btnAdd.setText("Add to Cart");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(102, 0, 51));
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setText("Category :");

        jLabel3.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setText("Color :");

        jLabel4.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 51));
        jLabel4.setText("Size :");

        jLabel5.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 51));
        jLabel5.setText("Fabric Type:");

        jLabel6.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 51));
        jLabel6.setText("Quantity :");

        cmbQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten" }));

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Men", "Women", "Kids", "Baby" }));
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });

        cmbColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Black", "Basic White", "Beige", "Red", "Blue", "Lemon Yellow", "Pink", " " }));
        cmbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColorActionPerformed(evt);
            }
        });

        cmbSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XL", "L", "M", "S", "XS", "6 Months", "12 Months", "18 Months", "New Born" }));

        cmbFabricType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cotton", "Polyester", "Cotton Polyester", "Satin", "Jersey", "Linen", "Fleece" }));

        jLabel7.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 51));
        jLabel7.setText("Text :");

        cmbText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Text", "Text" }));

        jLabel9.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 51));
        jLabel9.setText("Text Location:");

        cmbTextLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Front", "Back", "Sleeve Right", "Sleeve Left", "Both Sleeves" }));

        jLabel10.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 51));
        jLabel10.setText("Design Technique:");

        cmbDesignTechnique.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Printing", "Embroidery" }));
        cmbDesignTechnique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDesignTechniqueActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 51));
        jLabel11.setText("Style :");

        cmbStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tshirt", "Shirt", "Hoodies", "Sweatshirts", "Jackets", "Tank Tops", "Baby Bodysuits" }));
        cmbStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStyleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel1.setText("The Cloth Factory");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerWorkArea/clotjhes (1).gif"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 51));
        jLabel13.setText("Text to be printed :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFabricType, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDesignTechnique, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTextLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {backJButton, btnNext});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backJButton)
                    .addComponent(btnNext))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSize, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFabricType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTextLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbDesignTechnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {backJButton, btnNext});

    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof customerCareEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof StoreOrganization) {
                            mod = ((StoreOrganization) organization).getMol();
                        }

                    }
                }
            }
        }

        
        count++;
        PersonalisedOrderItem oi = order.addPersonalisedOrderItem();
        order.setCustomer(account.getEmployee());
        order.setOrderNumber(count);

        float price = 0;
        System.out.println("reached here setcategory");
        oi.getPersonaliseProduct().setCategory(cmbCategory.getSelectedItem().toString());
        oi.getPersonaliseProduct().setStyle(cmbColor.getSelectedItem().toString());
        oi.getPersonaliseProduct().setColor(cmbSize.getSelectedItem().toString());
        oi.getPersonaliseProduct().setSize(cmbFabricType.getSelectedItem().toString());
        oi.getPersonaliseProduct().setFabricType(cmbStyle.getSelectedItem().toString());
        oi.getPersonaliseProduct().setQuantity(cmbText.getSelectedItem().toString());
        oi.getPersonaliseProduct().setPrintText(cmbQuantity.getSelectedItem().toString());
        oi.getPersonaliseProduct().setTextLocation(cmbDesignTechnique.getSelectedItem().toString());
        oi.getPersonaliseProduct().setDesignTechnique(cmbTextLocation.getSelectedItem().toString());

        if (oi.getPersonaliseProduct().getCategory().equalsIgnoreCase("Men")) {
            price = price + 1400;
        } else if (oi.getPersonaliseProduct().getCategory().equalsIgnoreCase("Women")) {
            price = price + 2500;
        } else {
            price = price + 30000;
        }

        //
        if (oi.getPersonaliseProduct().getCategory().equalsIgnoreCase("Kids")) {
            price = price + 400;
        } else if (oi.getPersonaliseProduct().getCategory().equalsIgnoreCase("Baby")) {
            price = price + 500;

        } 
        //

        if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("T-shirts")) {
            price = price + 1000;
        } else if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("Shirts")) {
            price = price + 600;
        } else if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("Hoodies")) {
            price = price + 500;
        } else if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("Sweatshirts")) {
            price = price + 700;
        }
        else if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("Jackets")) {
            price = price + 700;
        }else if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("Tank Tops")) {
            price = price + 700;
        }else if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("Baby Bodysuits")) {
            price = price + 700;
        }

        //
        if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Basic Black")) {
            price = price + 100;
        } else if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Basic White")) {
            price = price + 200;
        } else if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Beige")) {
            price = price + 300;
        } else if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Blue")) {
            price = price + 400;
        } else if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Red")) {
            price = price + 500;
        }else if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Lemon Yellow")) {
            price = price + 500;
        }else if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Pink")) {
            price = price + 500;
        }

        //
        if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("XL")) {
            price = price + 100;
        } else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("L")) {
            price = price + 200;
        } else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("M")) {
            price = price + 300;
        } else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("S")) {
            price = price + 400;
        } else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("XS")) {
            price = price + 500;
        } else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("6 months")) {
            price = price + 600;
        }else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("12 months")) {
            price = price + 600;
        }else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("18 months")) {
            price = price + 600;
        }else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("24 months")) {
            price = price + 600;
        }else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("New Born")) {
            price = price + 600;
        }

        //
        if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Cotton")) {
            price = price + 100;
        } else if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Polyester")) {
            price = price + 200;
        } else if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Cotton Polyester")) {
            price = price + 300;
        } else if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Satin")) {
            price = price + 400;
        } else if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Jersy")) {
            price = price + 500;
        } else if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Linen")) {
            price = price + 600;
        } else if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Fleece")) {
            price = price + 700;
        }
        //
        
        if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("One")) {
            price = price + 100;
        } else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Two")) {
            price = price + 200;
        } else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Three")) {
            price = price + 300;
        } else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Four")) {
            price = price + 400;
        }else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Five")) {
            price = price + 400;
        }else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Six")) {
            price = price + 400;
        }else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Seven")) {
            price = price + 400;
        }else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Eight")) {
            price = price + 400;
        }else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Nine")) {
            price = price + 400;
        }else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Ten")) {
            price = price + 400;
        }
        
        //
        if (oi.getPersonaliseProduct().getPrintText().equalsIgnoreCase("No Text")) {
            price = price + 100;
        } else if (oi.getPersonaliseProduct().getPrintText().equalsIgnoreCase("Text")) {
            price = price + 200;
        }
        //
        if (oi.getPersonaliseProduct().getTextLocation().equalsIgnoreCase("Front Print")) {
            price = price + 100;
        } else if (oi.getPersonaliseProduct().getTextLocation().equalsIgnoreCase("Back Print")) {
            price = price + 200;
        } else if (oi.getPersonaliseProduct().getTextLocation().equalsIgnoreCase("Sleeve left")) {
            price = price + 200;
        }else if (oi.getPersonaliseProduct().getTextLocation().equalsIgnoreCase("Sleeve Right")) {
            price = price + 200;
        }else if (oi.getPersonaliseProduct().getTextLocation().equalsIgnoreCase("Both Sleeves")) {
            price = price + 200;
        }
        
        else if (oi.getPersonaliseProduct().getDesignTechnique().equalsIgnoreCase("Embroidery")) {
            price = price + 200;
        }else if (oi.getPersonaliseProduct().getDesignTechnique().equalsIgnoreCase("Print")) {
            price = price + 200;
        }

        oi.getPersonaliseProduct().setPrice(price);
        JOptionPane.showMessageDialog(null, "Product added!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        CustomerWorkAreaManagementJPanel vjp = new CustomerWorkAreaManagementJPanel(userProcessContainer, mod, order,account,customerOrganization, enterprise, business);
        userProcessContainer.add("ManageOrderJPanel", vjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNextActionPerformed

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void cmbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbColorActionPerformed

    private void cmbDesignTechniqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDesignTechniqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDesignTechniqueActionPerformed

    private void cmbStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStyleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStyleActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JComboBox cmbColor;
    private javax.swing.JComboBox<String> cmbDesignTechnique;
    private javax.swing.JComboBox<String> cmbFabricType;
    private javax.swing.JComboBox<String> cmbQuantity;
    private javax.swing.JComboBox<String> cmbSize;
    private javax.swing.JComboBox<String> cmbStyle;
    private javax.swing.JComboBox<String> cmbText;
    private javax.swing.JComboBox<String> cmbTextLocation;
    private javax.swing.JLabel customerName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
