/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerWorkArea;

import business.organization.CustomerOrganization;
import Business.customer.MasterOrderList;
import Business.customer.PersonalisedOrder;
import Business.customer.PersonalisedOrderItem;
//import business.customer.CustomizedOrderItem;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.enterprise.customerCareEnterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.StoreOrganization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mrunalbhalerao
 */
public class PersonalizeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonalizeJPanel
     */
    private JPanel userProcessContainer;
    private MasterOrderList mod;
    private CustomerOrganization customerOrganization;
    private UserAccount account;
    private Enterprise enterprise;
    private Ecosystem business;
    private static int count;
    
    public PersonalizeJPanel(JPanel userProcessContainer, Organization organization, UserAccount account, Enterprise enterprise, Ecosystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.customerOrganization = (CustomerOrganization) organization;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        
        customerTextField.setText(account.getUsername());
        
    }
    
        PersonalisedOrder order = new PersonalisedOrder();
        PersonalisedOrderItem oi = new PersonalisedOrderItem();
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        customerTextField = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbQuantity = new javax.swing.JComboBox<>();
        cmbCategory = new javax.swing.JComboBox();
        cmbColor = new javax.swing.JComboBox();
        cmbSize = new javax.swing.JComboBox<>();
        cmbFabricType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbText = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbTextLocation = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmbDesignTechnique = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbStyle = new javax.swing.JComboBox<>();

        backJButton.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jLabel8.setText("Hello!");

        customerTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        customerTextField.setEnabled(false);
        customerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTextFieldActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnNext.setText("next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jLabel2.setText("Category :");

        jLabel3.setText("Color :");

        jLabel4.setText("Size :");

        jLabel5.setText("Fabric Type:");

        jLabel6.setText("Quantity :");

        cmbQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten" }));

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Men", "Women", "Kids", "Baby" }));
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });

        cmbColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic Black", "Basic White", "Beige", "Red", "Blue", "Lemon Yellow", "Pink", " " }));
        cmbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColorActionPerformed(evt);
            }
        });

        cmbSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XL", "L", "M", "S", "XS", "6 Months", "12 Months", "18 Months", "New Born" }));

        cmbFabricType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cotton", "Polyester", "Cotton Polyester", "Satin", "Jersey", "Linen", "Fleece" }));

        jLabel7.setText("Text :");

        cmbText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Text", "Text" }));

        jLabel9.setText("Text Location:");

        cmbTextLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Front", "Back", "Sleeve Right", "Sleeve Left", "Both Sleeves" }));

        jLabel10.setText("Design Technique:");

        cmbDesignTechnique.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Printing", "Embroidery" }));
        cmbDesignTechnique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDesignTechniqueActionPerformed(evt);
            }
        });

        jLabel11.setText("Style :");

        cmbStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tshirt", "Shirt", "Hoodies", "Sweatshirts", "Jackets", "Tank Tops", "Baby Bodysuits" }));
        cmbStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStyleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(backJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnAdd)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNext)
                            .addComponent(customerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(76, 76, 76)
                                .addComponent(cmbFabricType, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(343, 343, 343)
                                .addComponent(cmbDesignTechnique, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(cmbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(46, 46, 46)
                                        .addComponent(cmbStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(184, 184, 184)
                                        .addComponent(jLabel6)
                                        .addGap(28, 28, 28)
                                        .addComponent(cmbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(184, 184, 184)
                                                .addComponent(jLabel7)
                                                .addGap(63, 63, 63))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel9))
                                                .addGap(10, 10, 10)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbTextLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnNext))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTextLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDesignTechnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cmbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cmbFabricType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void customerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTextFieldActionPerformed

    }//GEN-LAST:event_customerTextFieldActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof customerCareEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof StoreOrganization) {
                            mod = ((StoreOrganization) organization).getMol();
                        }

                    }
                }
            }
        }

        // add customised order item to the order
        count++;
        PersonalisedOrderItem oi = order.addPersonalisedOrderItem();
        order.setCustomer(account.getEmployee());
        order.setOrderNumber(count);

        float price = 0;
        System.out.println("reached here setcategory");
        oi.getPersonaliseProduct().setCategory(cmbCategory.getSelectedItem().toString());
        oi.getPersonaliseProduct().setStyle(cmbColor.getSelectedItem().toString());
        oi.getPersonaliseProduct().setColor(cmbSize.getSelectedItem().toString());
        oi.getPersonaliseProduct().setSize(cmbFabricType.getSelectedItem().toString());
        oi.getPersonaliseProduct().setFabricType(cmbStyle.getSelectedItem().toString());
        oi.getPersonaliseProduct().setQuantity(cmbText.getSelectedItem().toString());
        oi.getPersonaliseProduct().setPrintText(cmbQuantity.getSelectedItem().toString());
        oi.getPersonaliseProduct().setTextLocation(cmbDesignTechnique.getSelectedItem().toString());
        oi.getPersonaliseProduct().setDesignTechnique(cmbTextLocation.getSelectedItem().toString());

        if (oi.getPersonaliseProduct().getCategory().equalsIgnoreCase("Men")) {
            price = price + 1400;
        } else if (oi.getPersonaliseProduct().getCategory().equalsIgnoreCase("Women")) {
            price = price + 2500;
        } else {
            price = price + 30000;
        }

        //
        if (oi.getPersonaliseProduct().getCategory().equalsIgnoreCase("Kids")) {
            price = price + 400;
        } else if (oi.getPersonaliseProduct().getCategory().equalsIgnoreCase("Baby")) {
            price = price + 500;

        } 
        //

        if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("T-shirts")) {
            price = price + 1000;
        } else if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("Shirts")) {
            price = price + 600;
        } else if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("Hoodies")) {
            price = price + 500;
        } else if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("Sweatshirts")) {
            price = price + 700;
        }
        else if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("Jackets")) {
            price = price + 700;
        }else if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("Tank Tops")) {
            price = price + 700;
        }else if (oi.getPersonaliseProduct().getStyle().equalsIgnoreCase("Baby Bodysuits")) {
            price = price + 700;
        }

        //
        if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Basic Black")) {
            price = price + 100;
        } else if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Basic White")) {
            price = price + 200;
        } else if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Beige")) {
            price = price + 300;
        } else if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Blue")) {
            price = price + 400;
        } else if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Red")) {
            price = price + 500;
        }else if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Lemon Yellow")) {
            price = price + 500;
        }else if (oi.getPersonaliseProduct().getColor().equalsIgnoreCase("Pink")) {
            price = price + 500;
        }

        //
        if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("XL")) {
            price = price + 100;
        } else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("L")) {
            price = price + 200;
        } else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("M")) {
            price = price + 300;
        } else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("S")) {
            price = price + 400;
        } else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("XS")) {
            price = price + 500;
        } else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("6 months")) {
            price = price + 600;
        }else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("12 months")) {
            price = price + 600;
        }else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("18 months")) {
            price = price + 600;
        }else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("24 months")) {
            price = price + 600;
        }else if (oi.getPersonaliseProduct().getSize().equalsIgnoreCase("New Born")) {
            price = price + 600;
        }

        //
        if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Cotton")) {
            price = price + 100;
        } else if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Polyester")) {
            price = price + 200;
        } else if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Cotton Polyester")) {
            price = price + 300;
        } else if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Satin")) {
            price = price + 400;
        } else if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Jersy")) {
            price = price + 500;
        } else if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Linen")) {
            price = price + 600;
        } else if (oi.getPersonaliseProduct().getFabricType().equalsIgnoreCase("Fleece")) {
            price = price + 700;
        }
        //
        
        if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("One")) {
            price = price + 100;
        } else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Two")) {
            price = price + 200;
        } else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Three")) {
            price = price + 300;
        } else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Four")) {
            price = price + 400;
        }else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Five")) {
            price = price + 400;
        }else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Six")) {
            price = price + 400;
        }else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Seven")) {
            price = price + 400;
        }else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Eight")) {
            price = price + 400;
        }else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Nine")) {
            price = price + 400;
        }else if (oi.getPersonaliseProduct().getQuantity().equalsIgnoreCase("Ten")) {
            price = price + 400;
        }
        
        //
        if (oi.getPersonaliseProduct().getPrintText().equalsIgnoreCase("No Text")) {
            price = price + 100;
        } else if (oi.getPersonaliseProduct().getPrintText().equalsIgnoreCase("Text")) {
            price = price + 200;
        }
        //
        if (oi.getPersonaliseProduct().getTextLocation().equalsIgnoreCase("Front Print")) {
            price = price + 100;
        } else if (oi.getPersonaliseProduct().getTextLocation().equalsIgnoreCase("Back Print")) {
            price = price + 200;
        } else if (oi.getPersonaliseProduct().getTextLocation().equalsIgnoreCase("Sleeve left")) {
            price = price + 200;
        }else if (oi.getPersonaliseProduct().getTextLocation().equalsIgnoreCase("Sleeve Right")) {
            price = price + 200;
        }else if (oi.getPersonaliseProduct().getTextLocation().equalsIgnoreCase("Both Sleeves")) {
            price = price + 200;
        }
        
        else if (oi.getPersonaliseProduct().getDesignTechnique().equalsIgnoreCase("Embroidery")) {
            price = price + 200;
        }else if (oi.getPersonaliseProduct().getDesignTechnique().equalsIgnoreCase("Print")) {
            price = price + 200;
        }

        oi.getPersonaliseProduct().setPrice(price);
        JOptionPane.showMessageDialog(null, "Product added!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        CustomerWorkAreaManagementJPanel vjp = new CustomerWorkAreaManagementJPanel(userProcessContainer, mod, order,account,customerOrganization, enterprise, business);
        userProcessContainer.add("ManageOrderJPanel", vjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNextActionPerformed

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void cmbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbColorActionPerformed

    private void cmbDesignTechniqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDesignTechniqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDesignTechniqueActionPerformed

    private void cmbStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStyleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStyleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JComboBox cmbColor;
    private javax.swing.JComboBox<String> cmbDesignTechnique;
    private javax.swing.JComboBox<String> cmbFabricType;
    private javax.swing.JComboBox<String> cmbQuantity;
    private javax.swing.JComboBox<String> cmbSize;
    private javax.swing.JComboBox<String> cmbStyle;
    private javax.swing.JComboBox<String> cmbText;
    private javax.swing.JComboBox<String> cmbTextLocation;
    private javax.swing.JTextField customerTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
