/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReportManagerWorkArea;

import Business.BarChart.HazardousContentReport;
import Business.BarChart.Report;
import Business.customer.MasterOrderList;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.enterprise.productionEnterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.ReportOrganization;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author mrunalbhalerao
 */
public class HazardousContentReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HazardousContentReportJPanel
     */
    
    private MasterOrderList mod;
    private JPanel userProcessContainer;
    Report report ;
    private Ecosystem business;
    
    final String applicationTitle = "Hazardous Content Chart";
    final String chartTitle = "Hazardous Content Chart";
    float fabricTypeCEContent = 0;
    float fabricTypeWTContent = 0;
    float fabricTypeWContent = 0;
    
    float designTechniqueCEContent = 0;
    float designTechniqueWTContent = 0;
    float designTechniqueWContent = 0;
    
    float manufacturingProcessCEContent = 0;
    float manufacturingProcessWTContent = 0;
    float manufacturingProcessWContent = 0;

    
    public HazardousContentReportJPanel(JPanel userProcessContainer, MasterOrderList mod,Ecosystem business) {
        initComponents();
        
        this.mod = mod;
        this.report = new Report();
        this.userProcessContainer = userProcessContainer;
        this.business=business;
        
        addReportToOrganization();
        
        
        
        
    }
    
    public void addReportToOrganization(){
         for(Network network: business.getNetworkList())
        {
            for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())
            {
                if(enterprise instanceof productionEnterprise)
                {
                    for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList())
                    {
                        if(organization instanceof ReportOrganization)
                        {
                            ((ReportOrganization) organization).setReport(report);
                        }
                    }
                }
            }
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton7 = new javax.swing.JButton();
        reportDisplayjPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        airFilterjComboBox = new javax.swing.JComboBox<>();
        engineTypejComboBox = new javax.swing.JComboBox();
        generatePieChartjButton = new javax.swing.JButton();
        pieReportjPanel = new javax.swing.JPanel();
        generateGraphjButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        manufacturingProcessjComboBox = new javax.swing.JComboBox<>();

        backJButton7.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        backJButton7.setText("Back");
        backJButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton7ActionPerformed(evt);
            }
        });

        reportDisplayjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        reportDisplayjPanel.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        jLabel7.setText("Fabric Type");

        jLabel8.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        jLabel8.setText("Design Technique");

        airFilterjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cotton", "Polyester", "Polyester-Cotton", "Satin", "Jersey", "Linen", "Fleece" }));

        engineTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Printing", "Embroidery" }));
        engineTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineTypejComboBoxActionPerformed(evt);
            }
        });

        generatePieChartjButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        generatePieChartjButton.setText("Generate Cumulative Graph ");
        generatePieChartjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePieChartjButtonActionPerformed(evt);
            }
        });

        pieReportjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        generateGraphjButton1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        generateGraphjButton1.setText("Generate Graph");
        generateGraphjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateGraphjButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 18)); // NOI18N
        jLabel9.setText("Manufacturirng Process");

        manufacturingProcessjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bleaching", "Dyeing" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backJButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(generateGraphjButton1)
                                .addGap(473, 473, 473)
                                .addComponent(generatePieChartjButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(reportDisplayjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(pieReportjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(airFilterjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(engineTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(manufacturingProcessjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(405, 405, 405))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backJButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(manufacturingProcessjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(engineTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(airFilterjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(generatePieChartjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(generateGraphjButton1)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportDisplayjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pieReportjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton7ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton7ActionPerformed

    private void engineTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineTypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineTypejComboBoxActionPerformed

    private void generatePieChartjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePieChartjButtonActionPerformed

        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
        //setting values of the bar chart
        barchartdata.setValue(report.getCumCarbonEmission(), "Carbon Emission", "Carbon Emission");
        barchartdata.setValue(report.getCumWaterToxin(), "Carbon Emission", "Water Toxin");
        barchartdata.setValue(report.getCumWaste(), "Carbon Emission", "Waste");

        JFreeChart barchart = ChartFactory.createBarChart3D("Report", "TYPES", "Hazardous Content Value", barchartdata, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot p = barchart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame chartfn = new ChartFrame("REVENUE GENERATION", barchart, true);
        //initComponents();
        chartfn.setSize(650, 400);

        pieReportjPanel.removeAll();
        pieReportjPanel.add(chartfn.getChartPanel());
        pieReportjPanel.setVisible(true);
        pieReportjPanel.setEnabled(true);
        pieReportjPanel.validate();
    }//GEN-LAST:event_generatePieChartjButtonActionPerformed

    private void generateGraphjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateGraphjButton1ActionPerformed
        setValuesForGraph();
    }//GEN-LAST:event_generateGraphjButton1ActionPerformed

private void setValuesForGraph() {

        if (airFilterjComboBox.getSelectedItem().equals("Cotton")) {
            fabricTypeCEContent = (float) (fabricTypeCEContent + 3.0);
            fabricTypeWTContent = (float) (fabricTypeWTContent + 4.0);
            fabricTypeWContent = (float) (fabricTypeWContent + 3.4);
        } else if (airFilterjComboBox.getSelectedItem().equals("Polyester")) {
            fabricTypeCEContent = (float) (fabricTypeCEContent + 6.7);
            fabricTypeWTContent = (float) (fabricTypeWTContent + 8.8);
            fabricTypeWContent = (float) (fabricTypeWContent + 7.9);
        } else if (airFilterjComboBox.getSelectedItem().equals("Polyester-Cotton")) {
            fabricTypeCEContent = (float) (fabricTypeCEContent + 2.3);
            fabricTypeWTContent = (float) (fabricTypeWTContent + 5.4);
            fabricTypeWContent = (float) (fabricTypeWContent + 6.8);
        } else if (airFilterjComboBox.getSelectedItem().equals("Satin")) {
            fabricTypeCEContent = (float) (fabricTypeCEContent + 8.5);
            fabricTypeWTContent = (float) (fabricTypeWTContent + 9.02);
            fabricTypeWContent = (float) (fabricTypeWContent + 8.79);
        } else if (airFilterjComboBox.getSelectedItem().equals("Jersey")) {
            fabricTypeCEContent = (float) (fabricTypeCEContent + 2.8);
            fabricTypeWTContent = (float) (fabricTypeWTContent + 3.8);
            fabricTypeWContent = (float) (fabricTypeWContent + 3.48);
        }
        else if (airFilterjComboBox.getSelectedItem().equals("Linen")) {
            fabricTypeCEContent = (float) (fabricTypeCEContent + 2.8);
            fabricTypeWTContent = (float) (fabricTypeWTContent + 3.8);
            fabricTypeWContent = (float) (fabricTypeWContent + 3.48);
        }
        else if (airFilterjComboBox.getSelectedItem().equals("Fleece")) {
            fabricTypeCEContent = (float) (fabricTypeCEContent + 2.8);
            fabricTypeWTContent = (float) (fabricTypeWTContent + 3.8);
            fabricTypeWContent = (float) (fabricTypeWContent + 3.48);
        }

        if (engineTypejComboBox.getSelectedItem().equals("Printing")) {
            designTechniqueCEContent = (float) (designTechniqueCEContent + 8.8);
            designTechniqueWTContent = (float) (designTechniqueWTContent + 9.78);
            designTechniqueWContent = (float) (designTechniqueWContent + 9.0);
        } else if (engineTypejComboBox.getSelectedItem().equals("Embroidery")) {
            designTechniqueCEContent = (float) (designTechniqueCEContent + 6.87);
            designTechniqueWTContent = (float) (designTechniqueWTContent+ 8.85);
            designTechniqueWContent = (float) (designTechniqueWContent + 5.7);
        } 
        
        if (manufacturingProcessjComboBox.getSelectedItem().equals("Bleaching")) {
            manufacturingProcessCEContent = (float) (manufacturingProcessCEContent + 8.8);
            manufacturingProcessWTContent = (float) (manufacturingProcessWTContent + 9.78);
            manufacturingProcessWContent = (float) (manufacturingProcessWContent + 9.0);
        } else if (manufacturingProcessjComboBox.getSelectedItem().equals("Dyeing")) {
            manufacturingProcessCEContent = (float) (manufacturingProcessCEContent + 6.87);
            manufacturingProcessWTContent = (float) (manufacturingProcessWTContent + 8.85);
            manufacturingProcessWContent = (float) (manufacturingProcessWContent + 5.7);
        } 


        report.setCarbonEmissionFabricType(fabricTypeCEContent);
        report.setWaterToxinFabricType(fabricTypeWTContent);
        report.setWasteFabricType(fabricTypeWContent);

        report.setCarbonEmissionDesignTechnique(designTechniqueCEContent);
        report.setWaterToxinDesignTechnque(designTechniqueWTContent);
        report.setWasteDesignTechnique(designTechniqueWContent);

        report.setCarbonEmissionManufacturingProcess(manufacturingProcessCEContent);
        report.setWaterToxinManufacturingProcess(manufacturingProcessWTContent);
        report.setWasteManufacturingProcess(manufacturingProcessWContent);

        
        //For use in pie-chart   
        report.setCumCarbonEmission(fabricTypeCEContent + designTechniqueCEContent + manufacturingProcessCEContent);
        report.setCumWaterToxin(fabricTypeWTContent + designTechniqueWTContent + manufacturingProcessWTContent);
        report.setCumWaste(fabricTypeWContent + designTechniqueWContent + manufacturingProcessWContent);


        //initComponents();
        HazardousContentReport chart = new HazardousContentReport(applicationTitle, chartTitle, report);
        reportDisplayjPanel.removeAll();
        reportDisplayjPanel.add(chart.getChartPanel());
        reportDisplayjPanel.setVisible(true);
        reportDisplayjPanel.validate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> airFilterjComboBox;
    private javax.swing.JButton backJButton7;
    private javax.swing.JComboBox engineTypejComboBox;
    private javax.swing.JButton generateGraphjButton1;
    private javax.swing.JButton generatePieChartjButton;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> manufacturingProcessjComboBox;
    private javax.swing.JPanel pieReportjPanel;
    private javax.swing.JPanel reportDisplayjPanel;
    // End of variables declaration//GEN-END:variables
}
