/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DesignerWorkArea;

import Business.WorkQueue.CustomerCustomizedWorkRequest;
import business.ecosystem.Ecosystem;
import business.enterprise.Enterprise;
import business.organization.DesignOrganization;
import business.organization.ManufacturingOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jharnadoda
 */
public class DesignWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DesignWorkAreaJPanel
     */
     private JPanel userProcessContainer;
     private Enterprise enterprise;
    private DesignOrganization designOrganization;
    private UserAccount userAccount;
    private Ecosystem business;
    public DesignWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, Ecosystem business) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.designOrganization = (DesignOrganization) organization;
        this.userAccount = userAccount;
        this.business = business;

         populateDesignTable();
        //add enterprise name to label
        valueLabel.setText(enterprise.getName());
        orgValueLabel.setText(organization.getName());
    }
        public void populateDesignTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest wr : designOrganization.getWorkQueue().getWorkRequestList()) {

            Object[] row = new Object[5];
            CustomerCustomizedWorkRequest cw = (CustomerCustomizedWorkRequest) wr;
            row[0] = cw;
            row[1] = cw.getStoreSender() == null ? null : cw.getStoreSender().getEmployee().getName();
            row[2] = cw.getDesignerReceiver() == null ? null : cw.getDesignerReceiver().getEmployee().getName();
            row[3] = cw.getRequestDate();
            row[4] = cw.getStatus();
            model.addRow(row);

        }

    
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        designCompleteJButton = new javax.swing.JButton();
        requestProducerJButton = new javax.swing.JButton();
        assignToMeJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        refreshTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        orgValueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(102, 0, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        designCompleteJButton.setBackground(new java.awt.Color(204, 204, 255));
        designCompleteJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        designCompleteJButton.setForeground(new java.awt.Color(102, 0, 51));
        designCompleteJButton.setText("Design Complete");
        designCompleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designCompleteJButtonActionPerformed(evt);
            }
        });

        requestProducerJButton.setBackground(new java.awt.Color(204, 204, 255));
        requestProducerJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        requestProducerJButton.setForeground(new java.awt.Color(102, 0, 51));
        requestProducerJButton.setText("Request Production Team");
        requestProducerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestProducerJButtonActionPerformed(evt);
            }
        });

        assignToMeJButton.setBackground(new java.awt.Color(204, 204, 255));
        assignToMeJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        assignToMeJButton.setForeground(new java.awt.Color(102, 0, 51));
        assignToMeJButton.setText("Accept Request");
        assignToMeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(assignToMeJButton)
                .addGap(68, 68, 68)
                .addComponent(designCompleteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(requestProducerJButton)
                .addGap(0, 228, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignToMeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designCompleteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestProducerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 69, -1, -1));

        backJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(102, 0, 51));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 17, 77, 28));

        refreshTestJButton.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        refreshTestJButton.setForeground(new java.awt.Color(102, 0, 51));
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 28, 137, -1));

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("The Cloth Factory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 25, 650, 38));

        workRequestJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        workRequestJTable.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        workRequestJTable.setForeground(new java.awt.Color(102, 0, 5));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Sender", "Receiver", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 293, 780, 220));

        enterpriseLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(102, 0, 51));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 83, 105, 30));

        enterpriseLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(102, 0, 51));
        enterpriseLabel1.setText("Organization:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 119, 124, 26));

        valueLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(102, 0, 51));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 85, 84, -1));

        orgValueLabel.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        orgValueLabel.setForeground(new java.awt.Color(102, 0, 51));
        orgValueLabel.setText("<value>");
        add(orgValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 119, 84, 26));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void designCompleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designCompleteJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first ", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        CustomerCustomizedWorkRequest request = (CustomerCustomizedWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);

        request.setStatus("Design Complete");
        populateDesignTable();

    }//GEN-LAST:event_designCompleteJButtonActionPerformed

    private void assignToMeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first ", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        CustomerCustomizedWorkRequest request = (CustomerCustomizedWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        request.setDesignerReceiver(userAccount);
        request.setStatus("Pending With Design");
        populateDesignTable();
    }//GEN-LAST:event_assignToMeJButtonActionPerformed

    private void requestProducerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestProducerJButtonActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first ", "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }

        CustomerCustomizedWorkRequest cRequest = (CustomerCustomizedWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        //check the status for designer
        if (cRequest.getStatus().equals("Order Ready")) {
            JOptionPane.showMessageDialog(null, "Please complete the design first", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (cRequest.getStatus().equals("Pending With Design")) {
            JOptionPane.showMessageDialog(null, "The design is not ready", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (cRequest.getStatus().equals("Design Complete")) {
            cRequest.setStatus("Manufacture Order");
            cRequest.setDesignerSender(userAccount);
            userAccount.getWorkQueue().getWorkRequestList().add(cRequest);

            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof ManufacturingOrganization) {
                    organization.getWorkQueue().getWorkRequestList().add(cRequest);

                }

            }
            JOptionPane.showMessageDialog(null, " Design sent to Manufacturer for manufacturing", "Warning", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_requestProducerJButtonActionPerformed

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateDesignTable();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton designCompleteJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orgValueLabel;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestProducerJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
